#!/bin/sh

# This is just to allow for the same command (`./build`) to be run,
# even if the build steps and/or specific crap changes

# Get into the repository root first
cd $(dirname $0)

gulp
gulp finalize